from typing import ClassVar

tls_1_0: ProtocolVersion
tls_1_1: ProtocolVersion
tls_1_2: ProtocolVersion
tls_1_3: ProtocolVersion
tls_1_3_23: ProtocolVersion
tls_1_3_23_fb: ProtocolVersion
tls_1_3_26: ProtocolVersion
tls_1_3_26_fb: ProtocolVersion
tls_1_3_28: ProtocolVersion

class FizzClientContext:
    def __init__(self) -> None: ...
    def getDefaultShares(self, *args, **kwargs): ...
    def getSupportedAlpns(self) -> list[str]: ...
    def getSupportedCiphers(self, *args, **kwargs): ...
    def getSupportedGroups(self, *args, **kwargs): ...
    def getSupportedPskModes(self, *args, **kwargs): ...
    def getSupportedSigSchemes(self, *args, **kwargs): ...
    def getSupportedVersions(self) -> list[ProtocolVersion]: ...
    def setDefaultShares(self, arg0) -> None: ...
    def setSupportedAlpns(self, arg0: list[str]) -> None: ...
    def setSupportedCiphers(self, arg0) -> None: ...
    def setSupportedGroups(self, arg0) -> None: ...
    def setSupportedPskModes(self, arg0) -> None: ...
    def setSupportedSigSchemes(self, arg0) -> None: ...
    def setSupportedVersions(self, arg0: list[ProtocolVersion]) -> None: ...

class ProtocolVersion:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    tls_1_0: ClassVar[ProtocolVersion] = ...
    tls_1_1: ClassVar[ProtocolVersion] = ...
    tls_1_2: ClassVar[ProtocolVersion] = ...
    tls_1_3: ClassVar[ProtocolVersion] = ...
    tls_1_3_23: ClassVar[ProtocolVersion] = ...
    tls_1_3_23_fb: ClassVar[ProtocolVersion] = ...
    tls_1_3_26: ClassVar[ProtocolVersion] = ...
    tls_1_3_26_fb: ClassVar[ProtocolVersion] = ...
    tls_1_3_28: ClassVar[ProtocolVersion] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def add(arg0: int, arg1: int) -> int: ...
def versions() -> list[ProtocolVersion]: ...
