[build-system]
requires = ["scikit-build-core>=0.3.3", "pybind11", "pybind11-stubgen"]
build-backend = "scikit_build_core.build"

[project]
name = "fizzpy"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Ryan Walters", email = "ryan@walters.to"}]

[project.optional-dependencies]
test = ["pytest"]

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
cmake.build-type = "Release"
# cmake.verbose = true
# logging.level = "DEBUG"

[tool.scikit-build.cmake.define]
CMAKE_TOOLCHAIN_FILE = "./vcpkg/scripts/buildsystems/vcpkg.cmake"