"""Type stub for the compiled ``fizzpy._core`` extension.

Hand-authored from the pybind11 bindings in ``_core.cpp``. The real extension is
built by scikit-build-core; a stubgen-generated stub needs that build, so this
stub is maintained by hand and must track the bindings. It exists so the pure
Python facades type-check strictly against the native boundary.
"""

from collections.abc import Callable
from enum import IntEnum

class ProtocolVersion(IntEnum):
    tls_1_0 = ...
    tls_1_1 = ...
    tls_1_2 = ...
    tls_1_3 = ...
    tls_1_3_23 = ...
    tls_1_3_23_fb = ...
    tls_1_3_26 = ...
    tls_1_3_26_fb = ...
    tls_1_3_28 = ...

class NamedGroup(IntEnum):
    secp256r1 = ...
    secp384r1 = ...
    secp521r1 = ...
    x25519 = ...
    x448 = ...
    mlkem512 = ...
    mlkem768 = ...
    mlkem1024 = ...
    secp256r1_mlkem768 = ...
    x25519_mlkem768 = ...

class PskKeyExchangeMode(IntEnum):
    psk_ke = ...
    psk_dhe_ke = ...

class CipherSuite(IntEnum):
    TLS_AES_128_GCM_SHA256 = ...
    TLS_AES_256_GCM_SHA384 = ...
    TLS_CHACHA20_POLY1305_SHA256 = ...

class SignatureScheme(IntEnum):
    ecdsa_secp256r1_sha256 = ...
    ecdsa_secp384r1_sha384 = ...
    ecdsa_secp521r1_sha512 = ...
    rsa_pss_sha256 = ...
    rsa_pss_sha384 = ...
    rsa_pss_sha512 = ...
    ed25519 = ...
    ed448 = ...

class SendKeyShare(IntEnum):
    Always = ...
    WhenNecessary = ...

class FizzClientContext:
    def __init__(self) -> None: ...
    def setSupportedVersions(self, versions: list[ProtocolVersion]) -> None: ...
    def getSupportedVersions(self) -> list[ProtocolVersion]: ...
    def setSupportedCiphers(self, ciphers: list[CipherSuite]) -> None: ...
    def getSupportedCiphers(self) -> list[CipherSuite]: ...
    def setSupportedSigSchemes(self, schemes: list[SignatureScheme]) -> None: ...
    def getSupportedSigSchemes(self) -> list[SignatureScheme]: ...
    def setSupportedGroups(self, groups: list[NamedGroup]) -> None: ...
    def getSupportedGroups(self) -> list[NamedGroup]: ...
    def setSupportedPskModes(self, modes: list[PskKeyExchangeMode]) -> None: ...
    def getSupportedPskModes(self) -> list[PskKeyExchangeMode]: ...
    def setSupportedAlpns(self, alpns: list[str]) -> None: ...
    def getSupportedAlpns(self) -> list[str]: ...
    def setSendEarlyData(self, send: bool) -> None: ...
    def getSendEarlyData(self) -> bool: ...
    def setSendKeyShare(self, mode: SendKeyShare) -> None: ...
    def getSendKeyShare(self) -> SendKeyShare: ...

# Negotiated TLS parameters returned by ``TlsConnection.negotiated``. Keys:
# version, cipher, group, alpn, sni, peer_cert (str) and group_code (the numeric
# NamedGroup codepoint, int). Typed with an object value to stay a plain dict.
NegotiatedParams = dict[str, object]

class TlsConnection:
    """A single TLS 1.3 connection driven on the shared EventBase thread.

    Every async method takes a ``(resolve, reject)`` callback pair the core
    invokes (holding the GIL) from its background thread when the op completes.
    """

    def __init__(self) -> None: ...
    def connect(
        self,
        host: str,
        port: int,
        sni: str,
        alpns: list[str],
        groups: list[NamedGroup],
        verify: bool,
        ca_file: str,
        timeout_ms: int,
        extensions: list[tuple[int, bytes]],
        resolve: Callable[[None], None],
        reject: Callable[[BaseException], None],
    ) -> None: ...
    def wrap_fd(
        self,
        fd: int,
        sni: str,
        alpns: list[str],
        groups: list[NamedGroup],
        verify: bool,
        ca_file: str,
        timeout_ms: int,
        extensions: list[tuple[int, bytes]],
        resolve: Callable[[None], None],
        reject: Callable[[BaseException], None],
    ) -> None: ...
    def write(
        self,
        data: bytes,
        resolve: Callable[[None], None],
        reject: Callable[[BaseException], None],
    ) -> None: ...
    def read(
        self,
        resolve: Callable[[bytes], None],
        reject: Callable[[BaseException], None],
    ) -> None: ...
    def negotiated(self) -> NegotiatedParams: ...
    def close(self) -> None: ...
